import { Project } from '@/types/projectType';

export const projects: Project[] = [
  {
    id: 'paradiseHotel',
    techStack: [
      'Next.js',
      'Supabase',
      'TypeScript',
      'Prisma',
      'PostgreSQL',
      'Tailwind CSS',
      'Next-intl',
      'Radix UI',
      'React Hook Form',
      'Zod',
      'Framer Motion',
      'Vitest',
      'MSW',
      'Playwright',
    ],
    githubUrl: 'https://github.com/Onuryemez54/The-Paradise-Hotel',
    liveUrl: 'https://www.paradisehotel.live',
    image: '/projects/paradise-hotel.webp',
  },
  {
    id: 'travelRoute',
    techStack: [
      'React',
      'TypeScript',
      'Redux',
      'Tailwind CSS',
      'Leaflet',
      'Json-Server',
      'DatePicker',
      'React-hook-form',
      'Vitest',
      'MSW',
    ],
    githubUrl: 'https://github.com/Onuryemez54/Travel-Route-App',
    image: '/projects/travel-route.webp',
  },
  {
    id: 'movieApp',
    techStack: ['JavaScript', 'CSS', 'HTML', 'Tmdb API'],
    githubUrl: 'https://github.com/Onuryemez54/movie-app-javascript',
    image: '/projects/movie-app.webp',
  },
  {
    id: 'recipeApp',
    techStack: [
      'React',
      'TypeScript',
      'JavaScript',
      'MUI',
      'Emotion Styled',
      'Context API',
      'React Hook Form',
      'Jest',
      'Themealdb API',
    ],
    githubUrl: 'https://github.com/Onuryemez54/RecipeApp',
    image: '/projects/recipe-app.webp',
  },
  {
    id: 'quizApp',
    techStack: ['React', 'JavaScript', 'Context API', 'Json-Server'],
    githubUrl: 'https://github.com/Onuryemez54/React-Quiz-App',
    image: '/projects/quiz-app.webp',
  },
  {
    id: 'portfolio',
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Next-intl',
      'Radix UI',
      'React Hook Form',
      'Zod',
      'Framer Motion',
      'Resend',
      'Vercel',
      'Playwright',
    ],
    githubUrl: 'https://github.com/Onuryemez54/My-Portfolio-Website',
    liveUrl: 'https://onuryemez-dev.vercel.app',
    image: '/projects/portfolio.webp',
  },
];
