export enum TechStackCategory {
  FRONTEND = 'FRONTEND',
  BACKEND = 'BACKEND',
  MOBILE = 'MOBILE',
  TOOLS = 'TOOLS',
  TESTING = 'TESTING',
}

export enum ExpertiseCategory {
  EDUCATION = 'EDUCATION',
  CERTIFICATIONS = 'CERTIFICATIONS',
  EXPERIENCE = 'EXPERIENCE',
}

export enum DownloadableCertification {
  CODE2CAREER = 'CODE2CAREER',
  FREECODECAMP = 'FREECODECAMP',
  REACT_TESTING = 'REACT_TESTING',
  JAVASCRIPT = 'JAVASCRIPT',
}
